console.log("This is the first time using a console");
var firstname="Ehsan";
var secondname="Choudhury";
console.log(firstname);
console.log(secondname);
var bothnames=firstname.concat(secondname);
console.log(bothnames);
var length=bothnames.length;
console.log(length);
var caps=bothnames.toUpperCase();
console.log(caps);
var lowercase=bothnames.toLowerCase();
console.log(lowercase);
var sentence="cat car house door";
var replace=sentence.replace("door","window");
console.log(replace);
var square_root=Math.sqrt(169);
console.log(square_root);
var greater=Math.max(934,281);
console.log(greater);
var min=Math.min(93444,22381);
console.log(min);